version: '3.8'

services:
  dkron1:
    image: dkron/dkron
    container_name: dkron1
    ports:
      - "8080:8080"
    volumes:
      - ./dkron1.yml:/dkron.yml
    command: agent --config /dkron.yml
    networks:
      dkron_net:
        aliases:
          - dkron1

  dkron2:
    image: dkron/dkron
    container_name: dkron2
    ports:
      - "8081:8080"
    volumes:
      - ./dkron2.yml:/dkron.yml
    command: agent --config /dkron.yml
    networks:
      dkron_net:
        aliases:
          - dkron2

  dkron3:
    image: dkron/dkron
    container_name: dkron3
    ports:
      - "8082:8080"
    volumes:
      - ./dkron3.yml:/dkron.yml
    command: agent --config /dkron.yml
    networks:
      dkron_net:
        aliases:
          - dkron3

networks:
  dkron_net:
    driver: bridge
