apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dkron.fullname" . }}-envs
  labels:
    {{- include "dkron.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.envs }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
