apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dkron.fullname" . }}
  labels:
    {{- include "dkron.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
