apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dkron.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "dkron.serverSelectorLabels" . | nindent 6 }}
