apiVersion: v2
appVersion: 3.2.1
description: A Helm chart for dkron
icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
name: dkron
type: application
version: 2.0.3
